ALTER DATABASE dmhwiki OWNER TO pywiki;
-- GRANT USAGE, CREATE ON SCHEMA public TO pywiki;
-- ALTER SCHEMA public OWNER TO pywiki;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PUBLIC TO pywiki;
GRANT ALL ON ALL SEQUENCES IN SCHEMA PUBLIC TO pywiki;

